server:
  port: 9191
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  info:
    env:
      enabled: true

info:
  application:
    name: Springboot actuator example
    description: Springboot 2.0 enhancements
    artifact: Sspringboot2x-actuator
    version: v1.0
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect